import type {AssumptionItem,SimulationResult} from '../../types'
import {ACTION_LABEL,inr,lakh,pct} from '../../lib/format'
import type {Action} from '../../types'
import Panel from '../common/Panel'
const Row=({l,v,c=''}:{l:string;v:string;c?:string})=><div className="flex justify-between border-b border-line py-2.5 last:border-0"><span className="text-t2">{l}</span><b className={`animate-fade text-xl tabular-nums ${c}`}>{v}</b></div>
export default function BatchSimulationView({r,assumptions}:{r:SimulationResult;assumptions:AssumptionItem[]}){const i=r.impact
 return<><div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border border-line bg-s1 p-[18px]"><h2 className="font-semibold">Baseline (no intervention)</h2><Row l="Expected RTO rate" v={pct(r.baseline.rate)}/><Row l="Expected RTO orders" v={Math.round(r.baseline.rtoOrders).toLocaleString('en-IN')}/><Row l="Expected RTO loss" v={inr(r.baseline.loss)}/></div>
 <div className="rounded-lg border border-lo/40 bg-lo/5 p-[18px]"><h2 className="font-semibold text-lo">With RTOGuard</h2><Row l="Expected RTO rate" v={pct(r.rtoguard.rate)}/><Row l="Expected RTO orders" v={Math.round(r.rtoguard.rtoOrders).toLocaleString('en-IN')}/><Row l="Expected RTO loss" v={inr(r.rtoguard.loss)}/></div></div>
 <Panel className="mt-4" title="Business impact" sub={`${r.orderCount.toLocaleString('en-IN')} synthetic orders · RTO rate change ${i.rtoRateChangePoints} pts${r.festive?' · festive window (configured assumption)':''}`}><Row l="RTO loss avoided" v={inr(i.rtoLossAvoided)}/><Row l="Intervention cost" v={'− '+inr(i.interventionCost)}/><Row l="Conversion loss" v={'− '+inr(i.conversionLoss)}/><Row l="Net business impact" v={inr(i.netImpact)} c={i.netImpact>=0?'text-lo':'text-hi'}/></Panel>
 <div className="mt-4 rounded-lg border border-lo/40 bg-lo/5 p-5 text-center"><span className="text-t2">₹ saved per 1,000 orders</span><b className="block animate-fade text-[40px] tracking-tight text-lo">{inr(i.savedPer1000)}</b><span className="text-xs text-t3">{lakh(i.netImpact)} net across this batch</span></div>
 <Panel className="mt-4" title="Actions chosen by the backend">{Object.entries(r.rtoguard.actionCounts).map(([a,n])=><Row key={a} l={ACTION_LABEL[a as Action]??a} v={n.toLocaleString('en-IN')}/>)}</Panel><Panel className="mt-4" title="Simulation assumptions" sub="Returned by the backend · simulated, not observed results">{assumptions.map(({label:k,value:v})=><div key={k} className="flex justify-between gap-6 border-b border-line py-2 last:border-0"><span className="text-t2">{k}</span><span className="text-right">{v}</span></div>)}</Panel></>}
