export type RiskLevel='LOW'|'MEDIUM'|'HIGH'
/** Enums returned by the backend (app/services/action_recommendation.py) */
export type Action='SHIP_NORMAL'|'PARTIAL_DEPOSIT'|'CONFIRMATION'|'NO_COD_INTERVENTION'
export type Payment='COD'|'Prepaid'
export type CustomerType='New'|'Returning'|'Unknown'
export type OverrideReason='VIP_CUSTOMER'|'CUSTOMER_CONTACTED'|'REPEAT_BUSINESS'|'MANUAL_VERIFICATION'|'DATA_ISSUE'|'OTHER'
export interface Labeled{label:string;value:number}
export interface Order{id:string;customer:string;value:number;location:string;payment:Payment;customerType:CustomerType;date:string;riskScore:number;riskLevel:RiskLevel;recommendedAction:Action;expectedLoss:number;topFactors:string[];factors:RiskFactor[]}
export interface RiskFactor{key:string;name:string;contribution?:number}
export interface RiskAssessment{orderId:string;riskScore:number;riskLevel:RiskLevel;factors:RiskFactor[];modelNote?:string}
export interface Recommendation{orderId:string;riskScore:number;riskLevel:RiskLevel;action:Action;rationale:string;suggestedDeposit:number;topFactors:string[];probBefore:number;probAfter:number;lossBefore:number;lossAfter:number;rtoLossAvoided:number;interventionCost:number;conversionLoss:number;netImpact:number}
export interface ScoreFeatures{customerType:'NEW'|'RETURNING';pastOrders:number;pastRtos:number;orderValue:number;paymentMode:'COD'|'PREPAID';pincode:string;festiveWindow:boolean}
export interface Scored{order:Order;recommendation:Recommendation;modelNote:string}
export interface DecisionEvent{orderId:string;originalRiskScore:number;originalAction:Action;operatorAction:'ACCEPT'|'OVERRIDE';overrideAction?:Action;overrideReason?:OverrideReason;overrideNote?:string;at:string}
export interface OutcomeRecord{orderId:string;actualOutcome:'DELIVERED'|'RTO'|'PENDING';outcomeDate?:string}
export interface OperatorState{decision?:DecisionEvent;outcome?:OutcomeRecord}
export interface SimulationInput{orderCount:number;seed:number;festive:boolean}
export interface SimulationEconomics{rtoLossAvoided:number;interventionCost:number;conversionLoss:number;netImpact:number;rtoRateChangePoints:number;savedPer1000:number}
export interface SimulationResult{orderCount:number;festive:boolean;baseline:{rate:number;rtoOrders:number;loss:number};rtoguard:{rate:number;rtoOrders:number;loss:number;actionCounts:Record<string,number>};impact:SimulationEconomics;orders:Order[]}
export interface EvalMetrics{n:number;precision:number|null;recall:number|null;fpr:number|null;fnr:number|null}
export interface Evaluation{synthetic:EvalMetrics;operator:EvalMetrics;decisions:number;overrideRate:number|null;queueVolume:number;avgLatencySec:number|null;note:string}
export interface AssumptionItem{label:string;value:string}
export interface DashboardMetrics{orderCount:number;rtoRate:number;expectedLoss:number;highRiskOrders:number;netImpact:number;distribution:{level:RiskLevel;orders:number;loss:number}[]}
export interface AnalyticsData{rateByPayment:Labeled[];actions:Labeled[];lossByLevel:Labeled[]}
export interface Scenario{id:string;label:string;orderId:string;features:ScoreFeatures}
