import {useState} from 'react'
import type {Action,DecisionEvent,OperatorState,OutcomeRecord,OverrideReason} from '../../types'
import {ACTIONS,ACTION_LABEL,pct,REASONS,REASON_LABEL} from '../../lib/format'
interface P{orderId:string;riskScore:number;action:Action;state?:OperatorState;note:string;onDecide:(d:Omit<DecisionEvent,'at'>)=>Promise<unknown>;onOutcome:(o:OutcomeRecord)=>Promise<unknown>}
export default function DecisionPanel({orderId,riskScore,action,state,note,onDecide,onOutcome}:P){
 const[mode,setMode]=useState<'idle'|'override'>('idle'),[act,setAct]=useState<Action>(ACTIONS.find(a=>a!==action)!),[why,setWhy]=useState<OverrideReason>('MANUAL_VERIFICATION'),[txt,setTxt]=useState(''),[err,setErr]=useState(''),[busy,setBusy]=useState(false)
 const run=async(f:()=>Promise<unknown>)=>{setBusy(true);setErr('');try{await f();setMode('idle');setTxt('')}catch(e){setErr((e as Error).message)}finally{setBusy(false)}}
 const base={orderId,originalRiskScore:riskScore,originalAction:action},d=state?.decision,o=state?.outcome
 return<div className="rounded-lg border border-line bg-s1 p-5"><h2 className="font-semibold">Operator decision</h2>
 <p className="mb-3 text-xs text-t3">Model output is never changed: {pct(riskScore)} risk · {ACTION_LABEL[action]}</p>
 {d?<div className="mb-3 rounded-md bg-s2 p-3"><b>{d.operatorAction==='ACCEPT'?'Recommendation accepted':`Overridden → ${ACTION_LABEL[d.overrideAction!]}`}</b>{d.overrideReason&&<p className="text-t2">Reason: {REASON_LABEL[d.overrideReason]}{d.overrideNote&&` · ${d.overrideNote}`}</p>}<p className="text-xs text-t3">{new Date(d.at).toLocaleString()}</p></div>:mode==='idle'?<div className="mb-3 flex gap-2"><button className="btn btn-p" disabled={busy} onClick={()=>run(()=>onDecide({...base,operatorAction:'ACCEPT'}))}>Accept Recommendation</button><button className="btn" onClick={()=>setMode('override')}>Override</button></div>
 :<div className="mb-3 space-y-2"><select className="field" aria-label="Override action" value={act} onChange={e=>setAct(e.target.value as Action)}>{ACTIONS.map(a=><option key={a} value={a}>{ACTION_LABEL[a]}</option>)}</select><select className="field" aria-label="Override reason" value={why} onChange={e=>setWhy(e.target.value as OverrideReason)}>{REASONS.map(r=><option key={r} value={r}>{REASON_LABEL[r]}</option>)}</select><input className="field" placeholder="Note (optional)" value={txt} onChange={e=>setTxt(e.target.value)}/><div className="flex gap-2"><button className="btn btn-p" disabled={busy} onClick={()=>run(()=>onDecide({...base,operatorAction:'OVERRIDE',overrideAction:act,overrideReason:why,overrideNote:txt||undefined}))}>Confirm Override</button><button className="btn" onClick={()=>setMode('idle')}>Cancel</button></div></div>}
 <div className="border-t border-line pt-3"><div className="mb-2 text-xs text-t2">Actual outcome</div>{o?<b className={o.actualOutcome==='RTO'?'text-hi':'text-lo'}>{o.actualOutcome==='RTO'?'Returned to origin':'Delivered'} · {o.outcomeDate}</b>:<div className="flex items-center gap-2"><span className="text-t3">Pending</span>{(['DELIVERED','RTO'] as const).map(x=><button key={x} className="btn" disabled={busy} onClick={()=>run(()=>onOutcome({orderId,actualOutcome:x,outcomeDate:new Date().toISOString().slice(0,10)}))}>{x==='RTO'?'Record RTO':'Record Delivered'}</button>)}</div>}</div>
 {err&&<p role="alert" className="mt-3 text-hi">{err}</p>}<p className="mt-3 text-xs text-t3">{note}</p></div>}
